site_name: DocUTT
site_url: https://Greenfox73.github.io/DocUTT/
site_author: Jean-Sebastien RIGAUD
copyright: Copyright &copy; 2026 Jean-Sebastien RIGAUD
theme:
  logo: images/logo_utt.png
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - palette.toggle
    - palette.light
    - palette.dark
    - content.math

nav:
  - Home: index.md
  - Soutien mathématiques:
    - Cours:
      - Résolution d’équations du second degré: soutien_math/equation_2nd_degre.md
      - Logarithmes et exponentielles: soutien_math/logarithmes_et_exponentielles_cours.md
      - Calcul littéral: soutien_math/calcul_litteral_cours.md
      - Inégalités, Racines et Valeur Absolue: soutien_math/inegalites_racines_et_valeur_absolue_cours.md 
      - Dérivées et opérations: soutien_math/derivées_et_operations_cours.md
    - Exercices:
      - Simplification et agilité algébrique: soutien_math/simplification_et_agilite_algebrique_exos.md
      - Logarithmes et exponentielles: soutien_math/logarithmes_et_exponentielles_exos.md
      - Calcul littéral et DES: soutien_math/calcul_litteral_et_des_exos.md
      - Factorisation avancée: soutien_math/factorisation_avancee_exos.md
      - Second degré et changements de variable: soutien_math/second_degre_et_changements_de_variable_exos.md
      - Domaines, inéquations et algébre avancée: soutien_math/domaines_inequations_et_algebre_avancee_exos.md
      - Dérivées et opérations: soutien_math/derivées_et_operations_exos.md
    - Archives:
      - Calcul littéral: soutien_math/calcul_litteral_beta.md

  - Année 1:
    - Calendrier universitaire: annee_1/calendrier_universitaire.md
    - Semestre 1:
      - MA12:
        - Cours: annee_1/semestre_1/ma12/ma12_cours.md
        - TD: annee_1/semestre_1/ma12/ma12_td.md
        - TP: annee_1/semestre_1/ma12/ma12_tp.md
      - MA14: annee_1/semestre_1/ma14.md
      - PR15: annee_1/semestre_1/pr15.md
      - MA21: annee_1/semestre_1/ma21.md
      - AP1A: annee_1/semestre_1/ap1a.md
      - LE08: annee_1/semestre_1/le08.md
      - EV01: annee_1/semestre_1/ev01.md
      
    - Semestre 2:
      - CS: annee_1/semestre_2/semestre_2_cs.md
      - TM: annee_1/semestre_2/semestre_2_tm.md
      - EC: annee_1/semestre_2/semestre_2_ec.md
      - ME: annee_1/semestre_2/semestre_2_me.md
      - HT: annee_1/semestre_2/semestre_2_ht.md

markdown_extensions:
  - pymdownx.arithmatex:
      inline_syntax: ['$', '$']   # Pour les formules en ligne
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
- mathjax-config.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js